//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  aktualnosci: Aktualnosci;
  aktualnosciConnection: AktualnosciConnection;
  kalendarz: Kalendarz;
  kalendarzConnection: KalendarzConnection;
  galeria: Galeria;
  galeriaConnection: GaleriaConnection;
  dokumenty: Dokumenty;
  dokumentyConnection: DokumentyConnection;
  zarzad: Zarzad;
  zarzadConnection: ZarzadConnection;
  dzialania: Dzialania;
  dzialaniaConnection: DzialaniaConnection;
  strona: Strona;
  stronaConnection: StronaConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAktualnosciArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAktualnosciConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AktualnosciFilter>;
};


export type QueryKalendarzArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKalendarzConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KalendarzFilter>;
};


export type QueryGaleriaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGaleriaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
};


export type QueryDokumentyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDokumentyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DokumentyFilter>;
};


export type QueryZarzadArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryZarzadConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ZarzadFilter>;
};


export type QueryDzialaniaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDzialaniaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DzialaniaFilter>;
};


export type QueryStronaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStronaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StronaFilter>;
};

export type DocumentFilter = {
  aktualnosci?: InputMaybe<AktualnosciFilter>;
  kalendarz?: InputMaybe<KalendarzFilter>;
  galeria?: InputMaybe<GaleriaFilter>;
  dokumenty?: InputMaybe<DokumentyFilter>;
  zarzad?: InputMaybe<ZarzadFilter>;
  dzialania?: InputMaybe<DzialaniaFilter>;
  strona?: InputMaybe<StronaFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Aktualnosci | Kalendarz | Galeria | Dokumenty | Zarzad | Dzialania | Strona | Folder;

export type AktualnosciWpisy = {
  __typename?: 'AktualnosciWpisy';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
  img?: Maybe<Scalars['String']['output']>;
  data?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
};

export type Aktualnosci = Node & Document & {
  __typename?: 'Aktualnosci';
  wpisy?: Maybe<Array<Maybe<AktualnosciWpisy>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AktualnosciWpisyFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  img?: InputMaybe<ImageFilter>;
  data?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type AktualnosciFilter = {
  wpisy?: InputMaybe<AktualnosciWpisyFilter>;
};

export type AktualnosciConnectionEdges = {
  __typename?: 'AktualnosciConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Aktualnosci>;
};

export type AktualnosciConnection = Connection & {
  __typename?: 'AktualnosciConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AktualnosciConnectionEdges>>>;
};

export type KalendarzWydarzenia = {
  __typename?: 'KalendarzWydarzenia';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  dateText?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
};

export type Kalendarz = Node & Document & {
  __typename?: 'Kalendarz';
  wydarzenia?: Maybe<Array<Maybe<KalendarzWydarzenia>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KalendarzWydarzeniaFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  dateText?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type KalendarzFilter = {
  wydarzenia?: InputMaybe<KalendarzWydarzeniaFilter>;
};

export type KalendarzConnectionEdges = {
  __typename?: 'KalendarzConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Kalendarz>;
};

export type KalendarzConnection = Connection & {
  __typename?: 'KalendarzConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KalendarzConnectionEdges>>>;
};

export type GaleriaAlbumy = {
  __typename?: 'GaleriaAlbumy';
  title: Scalars['String']['output'];
  year: Scalars['String']['output'];
  photos?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  published?: Maybe<Scalars['Boolean']['output']>;
};

export type Galeria = Node & Document & {
  __typename?: 'Galeria';
  albumy?: Maybe<Array<Maybe<GaleriaAlbumy>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GaleriaAlbumyFilter = {
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  photos?: InputMaybe<ImageFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type GaleriaFilter = {
  albumy?: InputMaybe<GaleriaAlbumyFilter>;
};

export type GaleriaConnectionEdges = {
  __typename?: 'GaleriaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Galeria>;
};

export type GaleriaConnection = Connection & {
  __typename?: 'GaleriaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GaleriaConnectionEdges>>>;
};

export type DokumentyKategorie = {
  __typename?: 'DokumentyKategorie';
  id: Scalars['String']['output'];
  label: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
};

export type DokumentyDokumenty = {
  __typename?: 'DokumentyDokumenty';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  file: Scalars['String']['output'];
  downloadName?: Maybe<Scalars['String']['output']>;
  kategoria: Scalars['String']['output'];
  published?: Maybe<Scalars['Boolean']['output']>;
};

export type Dokumenty = Node & Document & {
  __typename?: 'Dokumenty';
  kategorie?: Maybe<Array<Maybe<DokumentyKategorie>>>;
  dokumenty?: Maybe<Array<Maybe<DokumentyDokumenty>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DokumentyKategorieFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type DokumentyDokumentyFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  file?: InputMaybe<ImageFilter>;
  downloadName?: InputMaybe<StringFilter>;
  kategoria?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type DokumentyFilter = {
  kategorie?: InputMaybe<DokumentyKategorieFilter>;
  dokumenty?: InputMaybe<DokumentyDokumentyFilter>;
};

export type DokumentyConnectionEdges = {
  __typename?: 'DokumentyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Dokumenty>;
};

export type DokumentyConnection = Connection & {
  __typename?: 'DokumentyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DokumentyConnectionEdges>>>;
};

export type ZarzadOsoby = {
  __typename?: 'ZarzadOsoby';
  imieNazwisko: Scalars['String']['output'];
  funkcja: Scalars['String']['output'];
  zdjecie: Scalars['String']['output'];
  opublikowane?: Maybe<Scalars['Boolean']['output']>;
};

export type Zarzad = Node & Document & {
  __typename?: 'Zarzad';
  osoby?: Maybe<Array<Maybe<ZarzadOsoby>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ZarzadOsobyFilter = {
  imieNazwisko?: InputMaybe<StringFilter>;
  funkcja?: InputMaybe<StringFilter>;
  zdjecie?: InputMaybe<ImageFilter>;
  opublikowane?: InputMaybe<BooleanFilter>;
};

export type ZarzadFilter = {
  osoby?: InputMaybe<ZarzadOsobyFilter>;
};

export type ZarzadConnectionEdges = {
  __typename?: 'ZarzadConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Zarzad>;
};

export type ZarzadConnection = Connection & {
  __typename?: 'ZarzadConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ZarzadConnectionEdges>>>;
};

export type DzialaniaPozycje = {
  __typename?: 'DzialaniaPozycje';
  tytul: Scalars['String']['output'];
  opis: Scalars['String']['output'];
  zdjecie: Scalars['String']['output'];
  opublikowane?: Maybe<Scalars['Boolean']['output']>;
};

export type Dzialania = Node & Document & {
  __typename?: 'Dzialania';
  pozycje?: Maybe<Array<Maybe<DzialaniaPozycje>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DzialaniaPozycjeFilter = {
  tytul?: InputMaybe<StringFilter>;
  opis?: InputMaybe<StringFilter>;
  zdjecie?: InputMaybe<ImageFilter>;
  opublikowane?: InputMaybe<BooleanFilter>;
};

export type DzialaniaFilter = {
  pozycje?: InputMaybe<DzialaniaPozycjeFilter>;
};

export type DzialaniaConnectionEdges = {
  __typename?: 'DzialaniaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Dzialania>;
};

export type DzialaniaConnection = Connection & {
  __typename?: 'DzialaniaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DzialaniaConnectionEdges>>>;
};

export type StronaNaglowek = {
  __typename?: 'StronaNaglowek';
  tytul: Scalars['String']['output'];
  podtytul: Scalars['String']['output'];
  zdjecie: Scalars['String']['output'];
};

export type StronaONas = {
  __typename?: 'StronaONas';
  tytul: Scalars['String']['output'];
  tresc: Scalars['String']['output'];
  zdjecie: Scalars['String']['output'];
  opisZdjecia: Scalars['String']['output'];
  coRobimy?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  czymSieZajmujemy?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type StronaKontaktPrzewodniczacy = {
  __typename?: 'StronaKontaktPrzewodniczacy';
  imieNazwisko: Scalars['String']['output'];
  telefon: Scalars['String']['output'];
};

export type StronaKontaktTelefony = {
  __typename?: 'StronaKontaktTelefony';
  numer: Scalars['String']['output'];
  opis: Scalars['String']['output'];
  alarmowy?: Maybe<Scalars['Boolean']['output']>;
};

export type StronaKontaktLinki = {
  __typename?: 'StronaKontaktLinki';
  nazwa: Scalars['String']['output'];
  adres: Scalars['String']['output'];
};

export type StronaKontakt = {
  __typename?: 'StronaKontakt';
  adres: Scalars['String']['output'];
  email: Scalars['String']['output'];
  facebook: Scalars['String']['output'];
  przewodniczacy?: Maybe<StronaKontaktPrzewodniczacy>;
  telefony?: Maybe<Array<Maybe<StronaKontaktTelefony>>>;
  linki?: Maybe<Array<Maybe<StronaKontaktLinki>>>;
};

export type Strona = Node & Document & {
  __typename?: 'Strona';
  naglowek?: Maybe<StronaNaglowek>;
  oNas?: Maybe<StronaONas>;
  kontakt?: Maybe<StronaKontakt>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StronaNaglowekFilter = {
  tytul?: InputMaybe<StringFilter>;
  podtytul?: InputMaybe<StringFilter>;
  zdjecie?: InputMaybe<ImageFilter>;
};

export type StronaONasFilter = {
  tytul?: InputMaybe<StringFilter>;
  tresc?: InputMaybe<StringFilter>;
  zdjecie?: InputMaybe<ImageFilter>;
  opisZdjecia?: InputMaybe<StringFilter>;
  coRobimy?: InputMaybe<StringFilter>;
  czymSieZajmujemy?: InputMaybe<StringFilter>;
};

export type StronaKontaktPrzewodniczacyFilter = {
  imieNazwisko?: InputMaybe<StringFilter>;
  telefon?: InputMaybe<StringFilter>;
};

export type StronaKontaktTelefonyFilter = {
  numer?: InputMaybe<StringFilter>;
  opis?: InputMaybe<StringFilter>;
  alarmowy?: InputMaybe<BooleanFilter>;
};

export type StronaKontaktLinkiFilter = {
  nazwa?: InputMaybe<StringFilter>;
  adres?: InputMaybe<StringFilter>;
};

export type StronaKontaktFilter = {
  adres?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  przewodniczacy?: InputMaybe<StronaKontaktPrzewodniczacyFilter>;
  telefony?: InputMaybe<StronaKontaktTelefonyFilter>;
  linki?: InputMaybe<StronaKontaktLinkiFilter>;
};

export type StronaFilter = {
  naglowek?: InputMaybe<StronaNaglowekFilter>;
  oNas?: InputMaybe<StronaONasFilter>;
  kontakt?: InputMaybe<StronaKontaktFilter>;
};

export type StronaConnectionEdges = {
  __typename?: 'StronaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Strona>;
};

export type StronaConnection = Connection & {
  __typename?: 'StronaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StronaConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAktualnosci: Aktualnosci;
  createAktualnosci: Aktualnosci;
  updateKalendarz: Kalendarz;
  createKalendarz: Kalendarz;
  updateGaleria: Galeria;
  createGaleria: Galeria;
  updateDokumenty: Dokumenty;
  createDokumenty: Dokumenty;
  updateZarzad: Zarzad;
  createZarzad: Zarzad;
  updateDzialania: Dzialania;
  createDzialania: Dzialania;
  updateStrona: Strona;
  createStrona: Strona;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAktualnosciArgs = {
  relativePath: Scalars['String']['input'];
  params: AktualnosciMutation;
};


export type MutationCreateAktualnosciArgs = {
  relativePath: Scalars['String']['input'];
  params: AktualnosciMutation;
};


export type MutationUpdateKalendarzArgs = {
  relativePath: Scalars['String']['input'];
  params: KalendarzMutation;
};


export type MutationCreateKalendarzArgs = {
  relativePath: Scalars['String']['input'];
  params: KalendarzMutation;
};


export type MutationUpdateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationCreateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationUpdateDokumentyArgs = {
  relativePath: Scalars['String']['input'];
  params: DokumentyMutation;
};


export type MutationCreateDokumentyArgs = {
  relativePath: Scalars['String']['input'];
  params: DokumentyMutation;
};


export type MutationUpdateZarzadArgs = {
  relativePath: Scalars['String']['input'];
  params: ZarzadMutation;
};


export type MutationCreateZarzadArgs = {
  relativePath: Scalars['String']['input'];
  params: ZarzadMutation;
};


export type MutationUpdateDzialaniaArgs = {
  relativePath: Scalars['String']['input'];
  params: DzialaniaMutation;
};


export type MutationCreateDzialaniaArgs = {
  relativePath: Scalars['String']['input'];
  params: DzialaniaMutation;
};


export type MutationUpdateStronaArgs = {
  relativePath: Scalars['String']['input'];
  params: StronaMutation;
};


export type MutationCreateStronaArgs = {
  relativePath: Scalars['String']['input'];
  params: StronaMutation;
};

export type DocumentUpdateMutation = {
  aktualnosci?: InputMaybe<AktualnosciMutation>;
  kalendarz?: InputMaybe<KalendarzMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  dokumenty?: InputMaybe<DokumentyMutation>;
  zarzad?: InputMaybe<ZarzadMutation>;
  dzialania?: InputMaybe<DzialaniaMutation>;
  strona?: InputMaybe<StronaMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  aktualnosci?: InputMaybe<AktualnosciMutation>;
  kalendarz?: InputMaybe<KalendarzMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  dokumenty?: InputMaybe<DokumentyMutation>;
  zarzad?: InputMaybe<ZarzadMutation>;
  dzialania?: InputMaybe<DzialaniaMutation>;
  strona?: InputMaybe<StronaMutation>;
};

export type AktualnosciWpisyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  img?: InputMaybe<Scalars['String']['input']>;
  data?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AktualnosciMutation = {
  wpisy?: InputMaybe<Array<InputMaybe<AktualnosciWpisyMutation>>>;
};

export type KalendarzWydarzeniaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  dateText?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type KalendarzMutation = {
  wydarzenia?: InputMaybe<Array<InputMaybe<KalendarzWydarzeniaMutation>>>;
};

export type GaleriaAlbumyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  photos?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GaleriaMutation = {
  albumy?: InputMaybe<Array<InputMaybe<GaleriaAlbumyMutation>>>;
};

export type DokumentyKategorieMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type DokumentyDokumentyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  file?: InputMaybe<Scalars['String']['input']>;
  downloadName?: InputMaybe<Scalars['String']['input']>;
  kategoria?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DokumentyMutation = {
  kategorie?: InputMaybe<Array<InputMaybe<DokumentyKategorieMutation>>>;
  dokumenty?: InputMaybe<Array<InputMaybe<DokumentyDokumentyMutation>>>;
};

export type ZarzadOsobyMutation = {
  imieNazwisko?: InputMaybe<Scalars['String']['input']>;
  funkcja?: InputMaybe<Scalars['String']['input']>;
  zdjecie?: InputMaybe<Scalars['String']['input']>;
  opublikowane?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ZarzadMutation = {
  osoby?: InputMaybe<Array<InputMaybe<ZarzadOsobyMutation>>>;
};

export type DzialaniaPozycjeMutation = {
  tytul?: InputMaybe<Scalars['String']['input']>;
  opis?: InputMaybe<Scalars['String']['input']>;
  zdjecie?: InputMaybe<Scalars['String']['input']>;
  opublikowane?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DzialaniaMutation = {
  pozycje?: InputMaybe<Array<InputMaybe<DzialaniaPozycjeMutation>>>;
};

export type StronaNaglowekMutation = {
  tytul?: InputMaybe<Scalars['String']['input']>;
  podtytul?: InputMaybe<Scalars['String']['input']>;
  zdjecie?: InputMaybe<Scalars['String']['input']>;
};

export type StronaONasMutation = {
  tytul?: InputMaybe<Scalars['String']['input']>;
  tresc?: InputMaybe<Scalars['String']['input']>;
  zdjecie?: InputMaybe<Scalars['String']['input']>;
  opisZdjecia?: InputMaybe<Scalars['String']['input']>;
  coRobimy?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  czymSieZajmujemy?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StronaKontaktPrzewodniczacyMutation = {
  imieNazwisko?: InputMaybe<Scalars['String']['input']>;
  telefon?: InputMaybe<Scalars['String']['input']>;
};

export type StronaKontaktTelefonyMutation = {
  numer?: InputMaybe<Scalars['String']['input']>;
  opis?: InputMaybe<Scalars['String']['input']>;
  alarmowy?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StronaKontaktLinkiMutation = {
  nazwa?: InputMaybe<Scalars['String']['input']>;
  adres?: InputMaybe<Scalars['String']['input']>;
};

export type StronaKontaktMutation = {
  adres?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  przewodniczacy?: InputMaybe<StronaKontaktPrzewodniczacyMutation>;
  telefony?: InputMaybe<Array<InputMaybe<StronaKontaktTelefonyMutation>>>;
  linki?: InputMaybe<Array<InputMaybe<StronaKontaktLinkiMutation>>>;
};

export type StronaMutation = {
  naglowek?: InputMaybe<StronaNaglowekMutation>;
  oNas?: InputMaybe<StronaONasMutation>;
  kontakt?: InputMaybe<StronaKontaktMutation>;
};

export type AktualnosciPartsFragment = { __typename: 'Aktualnosci', wpisy?: Array<{ __typename: 'AktualnosciWpisy', title: string, text: string, img?: string | null, data?: string | null, slug?: string | null, published?: boolean | null } | null> | null };

export type KalendarzPartsFragment = { __typename: 'Kalendarz', wydarzenia?: Array<{ __typename: 'KalendarzWydarzenia', title: string, date: string, dateText?: string | null, text?: string | null, published?: boolean | null } | null> | null };

export type GaleriaPartsFragment = { __typename: 'Galeria', albumy?: Array<{ __typename: 'GaleriaAlbumy', title: string, year: string, photos?: Array<string | null> | null, published?: boolean | null } | null> | null };

export type DokumentyPartsFragment = { __typename: 'Dokumenty', kategorie?: Array<{ __typename: 'DokumentyKategorie', id: string, label: string, icon?: string | null } | null> | null, dokumenty?: Array<{ __typename: 'DokumentyDokumenty', title: string, description?: string | null, file: string, downloadName?: string | null, kategoria: string, published?: boolean | null } | null> | null };

export type ZarzadPartsFragment = { __typename: 'Zarzad', osoby?: Array<{ __typename: 'ZarzadOsoby', imieNazwisko: string, funkcja: string, zdjecie: string, opublikowane?: boolean | null } | null> | null };

export type DzialaniaPartsFragment = { __typename: 'Dzialania', pozycje?: Array<{ __typename: 'DzialaniaPozycje', tytul: string, opis: string, zdjecie: string, opublikowane?: boolean | null } | null> | null };

export type StronaPartsFragment = { __typename: 'Strona', naglowek?: { __typename: 'StronaNaglowek', tytul: string, podtytul: string, zdjecie: string } | null, oNas?: { __typename: 'StronaONas', tytul: string, tresc: string, zdjecie: string, opisZdjecia: string, coRobimy?: Array<string | null> | null, czymSieZajmujemy?: Array<string | null> | null } | null, kontakt?: { __typename: 'StronaKontakt', adres: string, email: string, facebook: string, przewodniczacy?: { __typename: 'StronaKontaktPrzewodniczacy', imieNazwisko: string, telefon: string } | null, telefony?: Array<{ __typename: 'StronaKontaktTelefony', numer: string, opis: string, alarmowy?: boolean | null } | null> | null, linki?: Array<{ __typename: 'StronaKontaktLinki', nazwa: string, adres: string } | null> | null } | null };

export type AktualnosciQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AktualnosciQuery = { __typename?: 'Query', aktualnosci: { __typename: 'Aktualnosci', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, wpisy?: Array<{ __typename: 'AktualnosciWpisy', title: string, text: string, img?: string | null, data?: string | null, slug?: string | null, published?: boolean | null } | null> | null } };

export type AktualnosciConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AktualnosciFilter>;
}>;


export type AktualnosciConnectionQuery = { __typename?: 'Query', aktualnosciConnection: { __typename?: 'AktualnosciConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AktualnosciConnectionEdges', cursor: string, node?: { __typename: 'Aktualnosci', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, wpisy?: Array<{ __typename: 'AktualnosciWpisy', title: string, text: string, img?: string | null, data?: string | null, slug?: string | null, published?: boolean | null } | null> | null } | null } | null> | null } };

export type KalendarzQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type KalendarzQuery = { __typename?: 'Query', kalendarz: { __typename: 'Kalendarz', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, wydarzenia?: Array<{ __typename: 'KalendarzWydarzenia', title: string, date: string, dateText?: string | null, text?: string | null, published?: boolean | null } | null> | null } };

export type KalendarzConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KalendarzFilter>;
}>;


export type KalendarzConnectionQuery = { __typename?: 'Query', kalendarzConnection: { __typename?: 'KalendarzConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'KalendarzConnectionEdges', cursor: string, node?: { __typename: 'Kalendarz', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, wydarzenia?: Array<{ __typename: 'KalendarzWydarzenia', title: string, date: string, dateText?: string | null, text?: string | null, published?: boolean | null } | null> | null } | null } | null> | null } };

export type GaleriaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GaleriaQuery = { __typename?: 'Query', galeria: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, albumy?: Array<{ __typename: 'GaleriaAlbumy', title: string, year: string, photos?: Array<string | null> | null, published?: boolean | null } | null> | null } };

export type GaleriaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
}>;


export type GaleriaConnectionQuery = { __typename?: 'Query', galeriaConnection: { __typename?: 'GaleriaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GaleriaConnectionEdges', cursor: string, node?: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, albumy?: Array<{ __typename: 'GaleriaAlbumy', title: string, year: string, photos?: Array<string | null> | null, published?: boolean | null } | null> | null } | null } | null> | null } };

export type DokumentyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DokumentyQuery = { __typename?: 'Query', dokumenty: { __typename: 'Dokumenty', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kategorie?: Array<{ __typename: 'DokumentyKategorie', id: string, label: string, icon?: string | null } | null> | null, dokumenty?: Array<{ __typename: 'DokumentyDokumenty', title: string, description?: string | null, file: string, downloadName?: string | null, kategoria: string, published?: boolean | null } | null> | null } };

export type DokumentyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DokumentyFilter>;
}>;


export type DokumentyConnectionQuery = { __typename?: 'Query', dokumentyConnection: { __typename?: 'DokumentyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DokumentyConnectionEdges', cursor: string, node?: { __typename: 'Dokumenty', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kategorie?: Array<{ __typename: 'DokumentyKategorie', id: string, label: string, icon?: string | null } | null> | null, dokumenty?: Array<{ __typename: 'DokumentyDokumenty', title: string, description?: string | null, file: string, downloadName?: string | null, kategoria: string, published?: boolean | null } | null> | null } | null } | null> | null } };

export type ZarzadQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ZarzadQuery = { __typename?: 'Query', zarzad: { __typename: 'Zarzad', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, osoby?: Array<{ __typename: 'ZarzadOsoby', imieNazwisko: string, funkcja: string, zdjecie: string, opublikowane?: boolean | null } | null> | null } };

export type ZarzadConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ZarzadFilter>;
}>;


export type ZarzadConnectionQuery = { __typename?: 'Query', zarzadConnection: { __typename?: 'ZarzadConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ZarzadConnectionEdges', cursor: string, node?: { __typename: 'Zarzad', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, osoby?: Array<{ __typename: 'ZarzadOsoby', imieNazwisko: string, funkcja: string, zdjecie: string, opublikowane?: boolean | null } | null> | null } | null } | null> | null } };

export type DzialaniaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DzialaniaQuery = { __typename?: 'Query', dzialania: { __typename: 'Dzialania', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pozycje?: Array<{ __typename: 'DzialaniaPozycje', tytul: string, opis: string, zdjecie: string, opublikowane?: boolean | null } | null> | null } };

export type DzialaniaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DzialaniaFilter>;
}>;


export type DzialaniaConnectionQuery = { __typename?: 'Query', dzialaniaConnection: { __typename?: 'DzialaniaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DzialaniaConnectionEdges', cursor: string, node?: { __typename: 'Dzialania', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pozycje?: Array<{ __typename: 'DzialaniaPozycje', tytul: string, opis: string, zdjecie: string, opublikowane?: boolean | null } | null> | null } | null } | null> | null } };

export type StronaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StronaQuery = { __typename?: 'Query', strona: { __typename: 'Strona', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, naglowek?: { __typename: 'StronaNaglowek', tytul: string, podtytul: string, zdjecie: string } | null, oNas?: { __typename: 'StronaONas', tytul: string, tresc: string, zdjecie: string, opisZdjecia: string, coRobimy?: Array<string | null> | null, czymSieZajmujemy?: Array<string | null> | null } | null, kontakt?: { __typename: 'StronaKontakt', adres: string, email: string, facebook: string, przewodniczacy?: { __typename: 'StronaKontaktPrzewodniczacy', imieNazwisko: string, telefon: string } | null, telefony?: Array<{ __typename: 'StronaKontaktTelefony', numer: string, opis: string, alarmowy?: boolean | null } | null> | null, linki?: Array<{ __typename: 'StronaKontaktLinki', nazwa: string, adres: string } | null> | null } | null } };

export type StronaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StronaFilter>;
}>;


export type StronaConnectionQuery = { __typename?: 'Query', stronaConnection: { __typename?: 'StronaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StronaConnectionEdges', cursor: string, node?: { __typename: 'Strona', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, naglowek?: { __typename: 'StronaNaglowek', tytul: string, podtytul: string, zdjecie: string } | null, oNas?: { __typename: 'StronaONas', tytul: string, tresc: string, zdjecie: string, opisZdjecia: string, coRobimy?: Array<string | null> | null, czymSieZajmujemy?: Array<string | null> | null } | null, kontakt?: { __typename: 'StronaKontakt', adres: string, email: string, facebook: string, przewodniczacy?: { __typename: 'StronaKontaktPrzewodniczacy', imieNazwisko: string, telefon: string } | null, telefony?: Array<{ __typename: 'StronaKontaktTelefony', numer: string, opis: string, alarmowy?: boolean | null } | null> | null, linki?: Array<{ __typename: 'StronaKontaktLinki', nazwa: string, adres: string } | null> | null } | null } | null } | null> | null } };

export const AktualnosciPartsFragmentDoc = gql`
    fragment AktualnosciParts on Aktualnosci {
  __typename
  wpisy {
    __typename
    title
    text
    img
    data
    slug
    published
  }
}
    `;
export const KalendarzPartsFragmentDoc = gql`
    fragment KalendarzParts on Kalendarz {
  __typename
  wydarzenia {
    __typename
    title
    date
    dateText
    text
    published
  }
}
    `;
export const GaleriaPartsFragmentDoc = gql`
    fragment GaleriaParts on Galeria {
  __typename
  albumy {
    __typename
    title
    year
    photos
    published
  }
}
    `;
export const DokumentyPartsFragmentDoc = gql`
    fragment DokumentyParts on Dokumenty {
  __typename
  kategorie {
    __typename
    id
    label
    icon
  }
  dokumenty {
    __typename
    title
    description
    file
    downloadName
    kategoria
    published
  }
}
    `;
export const ZarzadPartsFragmentDoc = gql`
    fragment ZarzadParts on Zarzad {
  __typename
  osoby {
    __typename
    imieNazwisko
    funkcja
    zdjecie
    opublikowane
  }
}
    `;
export const DzialaniaPartsFragmentDoc = gql`
    fragment DzialaniaParts on Dzialania {
  __typename
  pozycje {
    __typename
    tytul
    opis
    zdjecie
    opublikowane
  }
}
    `;
export const StronaPartsFragmentDoc = gql`
    fragment StronaParts on Strona {
  __typename
  naglowek {
    __typename
    tytul
    podtytul
    zdjecie
  }
  oNas {
    __typename
    tytul
    tresc
    zdjecie
    opisZdjecia
    coRobimy
    czymSieZajmujemy
  }
  kontakt {
    __typename
    adres
    email
    facebook
    przewodniczacy {
      __typename
      imieNazwisko
      telefon
    }
    telefony {
      __typename
      numer
      opis
      alarmowy
    }
    linki {
      __typename
      nazwa
      adres
    }
  }
}
    `;
export const AktualnosciDocument = gql`
    query aktualnosci($relativePath: String!) {
  aktualnosci(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AktualnosciParts
  }
}
    ${AktualnosciPartsFragmentDoc}`;
export const AktualnosciConnectionDocument = gql`
    query aktualnosciConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AktualnosciFilter) {
  aktualnosciConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AktualnosciParts
      }
    }
  }
}
    ${AktualnosciPartsFragmentDoc}`;
export const KalendarzDocument = gql`
    query kalendarz($relativePath: String!) {
  kalendarz(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KalendarzParts
  }
}
    ${KalendarzPartsFragmentDoc}`;
export const KalendarzConnectionDocument = gql`
    query kalendarzConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KalendarzFilter) {
  kalendarzConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KalendarzParts
      }
    }
  }
}
    ${KalendarzPartsFragmentDoc}`;
export const GaleriaDocument = gql`
    query galeria($relativePath: String!) {
  galeria(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GaleriaParts
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const GaleriaConnectionDocument = gql`
    query galeriaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GaleriaFilter) {
  galeriaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GaleriaParts
      }
    }
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const DokumentyDocument = gql`
    query dokumenty($relativePath: String!) {
  dokumenty(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DokumentyParts
  }
}
    ${DokumentyPartsFragmentDoc}`;
export const DokumentyConnectionDocument = gql`
    query dokumentyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DokumentyFilter) {
  dokumentyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DokumentyParts
      }
    }
  }
}
    ${DokumentyPartsFragmentDoc}`;
export const ZarzadDocument = gql`
    query zarzad($relativePath: String!) {
  zarzad(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ZarzadParts
  }
}
    ${ZarzadPartsFragmentDoc}`;
export const ZarzadConnectionDocument = gql`
    query zarzadConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ZarzadFilter) {
  zarzadConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ZarzadParts
      }
    }
  }
}
    ${ZarzadPartsFragmentDoc}`;
export const DzialaniaDocument = gql`
    query dzialania($relativePath: String!) {
  dzialania(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DzialaniaParts
  }
}
    ${DzialaniaPartsFragmentDoc}`;
export const DzialaniaConnectionDocument = gql`
    query dzialaniaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DzialaniaFilter) {
  dzialaniaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DzialaniaParts
      }
    }
  }
}
    ${DzialaniaPartsFragmentDoc}`;
export const StronaDocument = gql`
    query strona($relativePath: String!) {
  strona(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StronaParts
  }
}
    ${StronaPartsFragmentDoc}`;
export const StronaConnectionDocument = gql`
    query stronaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StronaFilter) {
  stronaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StronaParts
      }
    }
  }
}
    ${StronaPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      aktualnosci(variables: AktualnosciQueryVariables, options?: C): Promise<{data: AktualnosciQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AktualnosciQueryVariables, query: string}> {
        return requester<{data: AktualnosciQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AktualnosciQueryVariables, query: string}, AktualnosciQueryVariables>(AktualnosciDocument, variables, options);
      },
    aktualnosciConnection(variables?: AktualnosciConnectionQueryVariables, options?: C): Promise<{data: AktualnosciConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AktualnosciConnectionQueryVariables, query: string}> {
        return requester<{data: AktualnosciConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AktualnosciConnectionQueryVariables, query: string}, AktualnosciConnectionQueryVariables>(AktualnosciConnectionDocument, variables, options);
      },
    kalendarz(variables: KalendarzQueryVariables, options?: C): Promise<{data: KalendarzQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KalendarzQueryVariables, query: string}> {
        return requester<{data: KalendarzQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KalendarzQueryVariables, query: string}, KalendarzQueryVariables>(KalendarzDocument, variables, options);
      },
    kalendarzConnection(variables?: KalendarzConnectionQueryVariables, options?: C): Promise<{data: KalendarzConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KalendarzConnectionQueryVariables, query: string}> {
        return requester<{data: KalendarzConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KalendarzConnectionQueryVariables, query: string}, KalendarzConnectionQueryVariables>(KalendarzConnectionDocument, variables, options);
      },
    galeria(variables: GaleriaQueryVariables, options?: C): Promise<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}> {
        return requester<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}, GaleriaQueryVariables>(GaleriaDocument, variables, options);
      },
    galeriaConnection(variables?: GaleriaConnectionQueryVariables, options?: C): Promise<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}> {
        return requester<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}, GaleriaConnectionQueryVariables>(GaleriaConnectionDocument, variables, options);
      },
    dokumenty(variables: DokumentyQueryVariables, options?: C): Promise<{data: DokumentyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DokumentyQueryVariables, query: string}> {
        return requester<{data: DokumentyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DokumentyQueryVariables, query: string}, DokumentyQueryVariables>(DokumentyDocument, variables, options);
      },
    dokumentyConnection(variables?: DokumentyConnectionQueryVariables, options?: C): Promise<{data: DokumentyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DokumentyConnectionQueryVariables, query: string}> {
        return requester<{data: DokumentyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DokumentyConnectionQueryVariables, query: string}, DokumentyConnectionQueryVariables>(DokumentyConnectionDocument, variables, options);
      },
    zarzad(variables: ZarzadQueryVariables, options?: C): Promise<{data: ZarzadQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZarzadQueryVariables, query: string}> {
        return requester<{data: ZarzadQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZarzadQueryVariables, query: string}, ZarzadQueryVariables>(ZarzadDocument, variables, options);
      },
    zarzadConnection(variables?: ZarzadConnectionQueryVariables, options?: C): Promise<{data: ZarzadConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZarzadConnectionQueryVariables, query: string}> {
        return requester<{data: ZarzadConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZarzadConnectionQueryVariables, query: string}, ZarzadConnectionQueryVariables>(ZarzadConnectionDocument, variables, options);
      },
    dzialania(variables: DzialaniaQueryVariables, options?: C): Promise<{data: DzialaniaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DzialaniaQueryVariables, query: string}> {
        return requester<{data: DzialaniaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DzialaniaQueryVariables, query: string}, DzialaniaQueryVariables>(DzialaniaDocument, variables, options);
      },
    dzialaniaConnection(variables?: DzialaniaConnectionQueryVariables, options?: C): Promise<{data: DzialaniaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DzialaniaConnectionQueryVariables, query: string}> {
        return requester<{data: DzialaniaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DzialaniaConnectionQueryVariables, query: string}, DzialaniaConnectionQueryVariables>(DzialaniaConnectionDocument, variables, options);
      },
    strona(variables: StronaQueryVariables, options?: C): Promise<{data: StronaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaQueryVariables, query: string}> {
        return requester<{data: StronaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaQueryVariables, query: string}, StronaQueryVariables>(StronaDocument, variables, options);
      },
    stronaConnection(variables?: StronaConnectionQueryVariables, options?: C): Promise<{data: StronaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaConnectionQueryVariables, query: string}> {
        return requester<{data: StronaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaConnectionQueryVariables, query: string}, StronaConnectionQueryVariables>(StronaConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  